name: bot
version: 1
handle:
    - hostaccess: if(path ~ "/cron/") deny "*"
cron:
    - description: post to sina micro blog
      url: /cron/bot.php
      schedule: every 15 mins
      timezone: Beijing
